blueprint:
  name: Automatyczne sterowanie oczyszczaczem powietrza (wieloma) z trybem manualnym
  description: |
    <br>
    <b>Ten Blueprint wcza i automatycznie steruje trybem oczyszczaczy powietrza na podstawie encji, przecznik贸w lub rcznych przecznik贸w na urzdzeniu oraz poziomu PM2.5.</b>
    <br><br>
     <b>Przeczniki, encje, obszary</b>: Oczyszczacze powietrza s wczane przez przecznik, encj lub obszar.<br>
     <b>Automatyczny tryb manualny</b>: Oczyszczacze powietrza przeczaj si w tryb manualny, gdy poziom PM2.5 wzronie powy偶ej zdefiniowanego progu.<br>
     <b>Automatyczny tryb auto</b>: Oczyszczacze powietrza przeczaj si w tryb auto, gdy poziom PM2.5 spadnie poni偶ej ustawionego progu.
  domain: automation
  input:
    manual_toggle:
      name: Przecznik lub encja manualna
      description: Przecznik lub encja do rcznego wczania oczyszczacza powietrza.
      selector:
        entity:
          domain:
            - input_boolean
            - switch
            - light
            - fan
            - binary_sensor
    manual_toggle_state:
      name: Stan przecznika lub encji manualnej
      description: Stan, w kt贸rym automatyzacja manualna jest wyzwalana (wczony lub wyczony)
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    pm2_5_sensor:
      name: Czujnik PM2.5
      description: Czujnik PM2.5 dla oczyszczaczy powietrza
      selector:
        entity:
          domain: sensor
    ppm_threshold:
      name: Pr贸g PM2.5 dla trybu auto
      description: Pr贸g (PPM) dla przeczenia oczyszczaczy powietrza w tryb auto.
      default: 50
      selector:
        number:
          min: 1
          max: 120
          step: 1
    ppm_increase_threshold:
      name: Pr贸g wzrostu PM2.5 dla trybu manualnego
      description: Pr贸g wzrostu (PPM) powy偶ej progu auto, dla przeczenia w tryb manualny.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
    manual_mode_percentage:
      name: Procent mocy w trybie manualnym
      description: Procent mocy wentylatora ustawiany w trybie manualnym (0-100).
      default: 60
      selector:
        number:
          min: 0
          max: 100
          step: 1
    fan_entities:
      name: Oczyszczacze powietrza
      description: Encje, obszary lub urzdzenia wybranych oczyszczaczy powietrza
      selector:
        target:
          entity:
            domain: fan

trigger:
  - platform: state
    entity_id: !input pm2_5_sensor
    id: pm25_change
  - platform: state
    entity_id: !input manual_toggle
    to: !input manual_toggle_state
    id: manual

condition: []

action:
  - choose:
      # Sterowanie oparte na PM2.5
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'pm25_change' }}"
        sequence:
          - delay:
              minutes: 3  # Poczekaj 3 minuty, aby ustabilizowa warto PM2.5
          - variables: # Dodajemy sekcj variables
              manual_threshold: "{{ float(inputs.ppm_threshold) + float(inputs.ppm_increase_threshold) }}" # Oblicz pr贸g manualny i zapisz jako zmienn
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pm2_5_sensor
                    below: !input ppm_threshold # Sprawd藕, czy PM2.5 jest poni偶ej progu auto
                sequence:
                  - service: fan.set_preset_mode
                    target: !input fan_entities
                    data:
                      preset_mode: auto
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pm2_5_sensor
                    above: "{{ manual_threshold }}" # U偶yj zmiennej manual_threshold
                sequence:
                  - service: fan.set_percentage
                    target: !input fan_entities
                    data:
                      percentage: !input manual_mode_percentage
            default: [] # Nic nie r贸b, jeli PM2.5 jest pomidzy progami
      # Rczne sterowanie
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'manual' }}"
        sequence:
          - service: fan.turn_on
            target: !input fan_entities
          - delay:
              minutes: 3
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: !input ppm_threshold # Sprawd藕, czy PM2.5 jest poni偶ej progu auto po rcznym wczeniu i wycz jeli tak
          - service: fan.turn_off
            target: !input fan_entities
mode: single
