blueprint:
  name: Sterowanie mocą oczyszczacza powietrza IKEA Starkvind na podstawie PM2.5
  description: Automatyczna regulacja mocy oczyszczacza powietrza IKEA Starkvind w zależności od odczytu PM2.5.
  domain: automation
  input:
    pm2_5_sensor:
      name: Czujnik PM2.5
      description: Czujnik PM2.5 dla oczyszczaczy powietrza
      selector:
        entity:
          domain:
          - sensor
    fan_entities:
      name: Oczyszczacze powietrza
      description: Wybierz encje, obszary lub urządzenia oczyszczaczy powietrza
      selector:
        target:
          entity:
          - domain:
            - fan

trigger:
  - platform: state
    entity_id: !input pm2_5_sensor

condition: []

action:
  - variables:
      pm_value: "{{ states(trigger.entity_id) | float }}"
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 10
        sequence:
          - service: fan.set_preset_mode
            target: !input fan_entities
            data:
              preset_mode: auto
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 14
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 20
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 18
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 30
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 24
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 40
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 31
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 60
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: 51
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 80
      - conditions:
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            above: 50
        sequence:
          - service: fan.set_percentage
            target: !input fan_entities
            data:
              percentage: 100

mode: single
