blueprint:
  name: Automatyczne sterowanie oczyszczaczem powietrza (wieloma) z trybem manualnym
  description: |
    <br>
    <b>📘Ten Blueprint włącza i automatycznie steruje trybem oczyszczaczy powietrza na podstawie encji, przełączników lub ręcznych przełączników na urządzeniu oraz poziomu PM2.5.</b>
  domain: automation
  input:
    manual_toggle:
      name: Przełącznik lub encja manualna
      description: Przełącznik lub encja do ręcznego włączania oczyszczacza powietrza.
      selector:
        entity:
          domain:
            - input_boolean
            - switch
            - light
            - fan
            - binary_sensor
    manual_toggle_state:
      name: Stan przełącznika lub encji manualnej
      description: Stan, w którym automatyzacja manualna jest wyzwalana (włączony lub wyłączony)
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    pm2_5_sensor:
      name: Czujnik PM2.5
      description: Czujnik PM2.5 dla oczyszczaczy powietrza
      selector:
        entity:
          domain: sensor
    ppm_threshold:
      name: Próg PM2.5 dla trybu auto
      description: Próg (PPM) dla przełączenia oczyszczaczy powietrza w tryb auto.
      default: 50
      selector:
        number:
          min: 1
          max: 120
          step: 1
    ppm_increase_threshold:
      name: Próg wzrostu PM2.5 dla trybu manualnego
      description: Próg wzrostu (PPM) powyżej progu auto, dla przełączenia w tryb manualny.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
    manual_mode_percentage:
      name: Procent mocy w trybie manualnym
      description: Procent mocy wentylatora ustawiany w trybie manualnym (0-100).
      default: 60
      selector:
        number:
          min: 0
          max: 100
          step: 1
    fan_entities:
      name: Oczyszczacze powietrza
      description: Encje, obszary lub urządzenia wybranych oczyszczaczy powietrza
      selector:
        target:
          entity:
            domain: fan

trigger:
  - platform: state
    entity_id: !input pm2_5_sensor
    id: pm25_change
  - platform: state
    entity_id: !input manual_toggle
    to: !input manual_toggle_state
    id: manual

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'pm25_change' }}"
        sequence:
          - delay:
              minutes: 3
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input pm2_5_sensor
                    below: !input ppm_threshold
                sequence:
                  - service: fan.set_preset_mode
                    target: !input fan_entities
                    data:
                      preset_mode: auto
              - conditions:
                  - condition: template
                    value_template: >
                      {{
                        states('sensor.' + trigger.to_state.entity_id.split('.')[1]) | float >
                        (ppm_threshold + ppm_increase_threshold)
                      }}
                sequence:
                  - service: fan.set_percentage
                    target: !input fan_entities
                    data:
                      percentage: !input manual_mode_percentage
            default: []
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'manual' }}"
        sequence:
          - service: fan.turn_on
            target: !input fan_entities
          - delay:
              minutes: 3
          - condition: numeric_state
            entity_id: !input pm2_5_sensor
            below: !input ppm_threshold
          - service: fan.turn_off
            target: !input fan_entities
mode: single
